In [1]:
import pandas as pd

In [9]:
covid = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/who_covid_19_situation_reports/who_covid_19_sit_rep_time_series/who_covid_19_sit_rep_time_series.csv')

In [10]:
covid.head()

,Province/States,Country/Region,WHO region,1/21/2020,1/22/2020,1/23/2020,1/24/2020,1/25/2020,1/26/2020,1/27/2020,...,3/12/2020,3/13/2020,3/14/2020,3/15/2020,3/16/2020,3/17/2020,3/18/2020,3/19/2020,3/20/2020,3/21/2020
0,Confirmed,Globally,NaN,282.0,314.0,581.0,846.0,1320.0,2014.0,2798.0,...,125048.0,132758.0,142539.0,153517.0,167515.0,179111.0,191127.0,209839.0,234073.0,266073.0
1,Deaths,Globally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,7426.0,7807.0,8778.0,9840.0,11184.0
2,Confirmed,China,Western Pacific Region,278.0,309.0,571.0,830.0,1297.0,1985.0,2741.0,...,80981.0,80991.0,81021.0,81048.0,81077.0,81116.0,81116.0,81174.0,81300.0,81416.0
3,Confirmed,Outside of China,NaN,4.0,5.0,10.0,16.0,23.0,29.0,57.0,...,44067.0,51767.0,61518.0,72469.0,86438.0,97995.0,110011.0,128665.0,152773.0,184657.0
4,Deaths,China,Western Pacific Region,NaN,NaN,NaN,NaN,NaN,NaN,80.0,...,3173.0,4955.0,3194.0,3204.0,3218.0,3231.0,3231.0,3242.0,3253.0,3261.0

In [11]:
covid = covid.melt(id_vars=["Country/Region","Province/States","WHO region"], 
        var_name="date", 
        value_name="Value")

In [12]:
covid.head()

     Country/Region Province/States              WHO region       date Value
0          Globally       Confirmed                     NaN  1/21/2020   282
1          Globally          Deaths                     NaN  1/21/2020   NaN
2             China       Confirmed  Western Pacific Region  1/21/2020   278
3  Outside of China       Confirmed                     NaN  1/21/2020     4
4             China          Deaths  Western Pacific Region  1/21/2020   NaN